### PR TITLE
Fixed Extra Messages After Vote

### LINKED ISSUE #6: Bug #1
Hi Arechi, I wanted to report a new CallVote bug that occurs on my servers, so when I make a new callvote "successful" I wait maximum 5 minutes on the server and it shows again that "successful vote" on the server, it's like from new but delayed... 
You can check to correct the bugs and see other errors. Thanks for reading.

Best Regards, Mihail

### PR DESCRIPTION
**Pull request by ButteredToast26**
Fixed code which originally caused an issue with additional success/failure messages being sent after a vote.

### CODE REVIEW

File: IVote.cs [hunk 1]
```diff
@@ -13,6 +14,10 @@ public interface IVote
 
         VoteStatus Status { get; set; }
 
+        Coroutine thisCoroutine1 { get; set; }
+
+        Coroutine thisCoroutine2 { get; set; }
+
```
Comment (Arechii) [inline IVote.cs]: This should not be enforced by the interface since third party vote implementations could use tasks instead of coroutines for example to handle cooldowns and such.

File: Vote.cs [hunk 2]
```diff
@@ -19,6 +19,10 @@ public class Vote : IVote
 
         public VoteStatus Status { get; set; } = VoteStatus.Ready;
 
+        public Coroutine thisCoroutine1 { get; set; }
+
+        public Coroutine thisCoroutine2 { get; set; }
+
```
Comment (Arechii) [inline Vote.cs]: Perhaps these should be private and named properly?
```suggestion
        private Coroutine _startCoroutine;

        private Coroutine _cooldownCoroutine;

```

File: Vote.cs [hunk 3]
```diff
@@ -54,14 +48,15 @@ public void Start(List<string> arguments)
             Arguments = arguments;
 
             SendMessage("START", Settings.Alias);
-            StartCoroutine(Start());
+
+            thisCoroutine1 = Plugin.Instance.StartCoroutine(Start());
```
Comment (Arechii) [inline Vote.cs]:
```suggestion
            _startCoroutine = Plugin.Instance.StartCoroutine(Start());
```

File: Vote.cs [hunk 4]
```diff
@@ -93,7 +88,7 @@ public void AddVote(UnturnedPlayer player)
 
             if (GetResult() != VoteResult.Success) return;
 
-            StopCoroutine(Start());
+            Plugin.Instance.StopCoroutine(thisCoroutine1);
```
Comment (Arechii) [inline Vote.cs]:
```suggestion
            Plugin.Instance.StopCoroutine(_startCoroutine);
```

File: Vote.cs [hunk 5]
```diff
@@ -121,7 +116,9 @@ public void Cooldown()
             Status = VoteStatus.CoolingDown;
 
             SendMessage("COOLDOWN", Settings.CooldownTime);
-            StartCoroutine(Cooldown(Settings.CooldownTime));
+            thisCoroutine2 = Plugin.Instance.StartCoroutine(Cooldown(Settings.CooldownTime));
+
+            Plugin.Instance.StopCoroutine(thisCoroutine1);
```
Comment (Arechii) [inline Vote.cs]:
```suggestion

            _cooldownCoroutine = Plugin.Instance.StartCoroutine(Cooldown(Settings.CooldownTime));

            Plugin.Instance.StopCoroutine(_startCoroutine);
```

**Review by Arechii — CHANGES_REQUESTED** [review]
Thank you for the pull request! I've left some comments that should be addressed before the merge.

**Comment by ButteredToast26** [comment]
I resolved your requested changes in the project and requested a re-review. Thank you for your time :)

**Comment by Arechii** [comment]
Thanks!
